[package]
name = "financequest"
version = "0.1.0"
edition = "2021"
description = "FinanceQuest — Campus Edition"

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }