name: Tauri Linux Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri app
        env:
          TAURI_PRIVATE_KEY: ""
          TAURI_KEY_PASSWORD: ""
        run: npm run tauri:build

      - name: Show bundle tree
        run: ls -laR src-tauri/target/release/bundle || true

      # Create comprehensive Linux package
      - name: Create Linux Complete Package
        run: |
          mkdir -p dist/FinanceQuest-Linux-v0.1.0
          
          # Copy AppImage
          cp src-tauri/target/release/bundle/appimage/*.AppImage dist/FinanceQuest-Linux-v0.1.0/ 2>/dev/null || true
          
          # Copy DEB package
          cp src-tauri/target/release/bundle/deb/*.deb dist/FinanceQuest-Linux-v0.1.0/ 2>/dev/null || true
          
          # Create portable executable folder
          mkdir -p dist/FinanceQuest-Linux-v0.1.0/Portable
          cp src-tauri/target/release/financequest dist/FinanceQuest-Linux-v0.1.0/Portable/
          cp icons/icon.png dist/FinanceQuest-Linux-v0.1.0/Portable/ 2>/dev/null || true
          
          # Copy documentation
          cp LICENSE dist/FinanceQuest-Linux-v0.1.0/LICENSE.txt 2>/dev/null || true
          cp INSTALL_LINUX.md dist/FinanceQuest-Linux-v0.1.0/INSTALL_GUIDE.txt 2>/dev/null || true
          cp README.md dist/FinanceQuest-Linux-v0.1.0/README.txt 2>/dev/null || true
          
          # Create ZIP
          cd dist
          zip -r FinanceQuest-Linux-v0.1.0-Complete.zip FinanceQuest-Linux-v0.1.0/

      - name: Upload Linux Complete Package
        uses: actions/upload-artifact@v4
        with:
          name: FinanceQuest-Linux-Complete
          path: dist/FinanceQuest-Linux-v0.1.0-Complete.zip
