name: Tauri macOS Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri app (Universal)
        env:
          TAURI_PRIVATE_KEY: ""
          TAURI_KEY_PASSWORD: ""
        run: npm run tauri:build -- --target universal-apple-darwin

      - name: Show bundle tree
        run: ls -laR src-tauri/target/universal-apple-darwin/release/bundle || true

      # Create comprehensive macOS package
      - name: Create macOS Complete Package
        run: |
          mkdir -p dist/FinanceQuest-macOS-v0.1.0
          
          # Copy DMG installer
          cp src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg dist/FinanceQuest-macOS-v0.1.0/ 2>/dev/null || true
          
          # Copy documentation
          cp LICENSE dist/FinanceQuest-macOS-v0.1.0/LICENSE.txt 2>/dev/null || true
          cp INSTALL_MACOS.md dist/FinanceQuest-macOS-v0.1.0/INSTALL_GUIDE.txt 2>/dev/null || true
          cp README.md dist/FinanceQuest-macOS-v0.1.0/README.txt 2>/dev/null || true
          
          # Create ZIP
          cd dist
          zip -r FinanceQuest-macOS-v0.1.0-Complete.zip FinanceQuest-macOS-v0.1.0/

      - name: Upload macOS Complete Package
        uses: actions/upload-artifact@v4
        with:
          name: FinanceQuest-macOS-Complete
          path: dist/FinanceQuest-macOS-v0.1.0-Complete.zip
