name: Tauri Windows Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri app
        env:
          TAURI_PRIVATE_KEY: ""
          TAURI_KEY_PASSWORD: ""
        run: npm run tauri build

      - name: Show bundle tree
        run: Get-ChildItem -Recurse src-tauri\target\release\bundle

      - name: Upload MSI Installer
        uses: actions/upload-artifact@v4
        with:
          name: FinanceQuest-Windows-MSI
          path: src-tauri/target/release/bundle/msi/*.msi

      - name: Upload NSIS Installer
        uses: actions/upload-artifact@v4
        with:
          name: FinanceQuest-Windows-NSIS
          path: src-tauri/target/release/bundle/nsis/*.exe

      # Optional: Create portable folder
      - name: Create portable folder
        run: |
          $appName = "FinanceQuest"
          $sourceDir = "src-tauri\target\release"
          $portableDir = "dist\${appName}-Windows-Portable"
          
          New-Item -ItemType Directory -Force -Path $portableDir
          
          Copy-Item "$sourceDir\${appName}.exe" $portableDir
          Copy-Item "icons\icon.ico" "$portableDir\icon.ico"
          
          # Create desktop.ini for folder icon
          Set-Content -Path "$portableDir\desktop.ini" -Value "[.ShellClassInfo]`r`nIconResource=icon.ico,0"
          attrib +s $portableDir
          attrib +h "$portableDir\desktop.ini"
          
          Compress-Archive -Path "$portableDir\*" -DestinationPath "dist\${appName}-Windows-Portable.zip"

      - name: Upload Portable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: FinanceQuest-Windows-Portable
          path: dist/FinanceQuest-Windows-Portable.zip
          if-no-files-found: ignore
