name: Windows Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@^2.8.4

      - name: Build Tauri app (Windows)
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: tauri build

      - name: Show dist tree
        run: Get-ChildItem -Recurse src-tauri\target\release\bundle

      - name: Upload MSI Installer
        uses: actions/upload-artifact@v4
        with:
          name: FinanceQuest-Windows-MSI
          path: src-tauri/target/release/bundle/msi/*.msi
          if-no-files-found: warn

      - name: Upload NSIS Installer
        uses: actions/upload-artifact@v4
        with:
          name: FinanceQuest-Windows-NSIS
          path: src-tauri/target/release/bundle/nsis/*.exe
          if-no-files-found: ignore

      - name: Create Portable ZIP
        run: |
          $exePath = Get-ChildItem -Path "src-tauri\target\release" -Filter "*.exe" -Recurse | Where-Object { $_.Directory.Name -eq "release" } | Select-Object -First 1
          if ($exePath) {
            New-Item -ItemType Directory -Force -Path "portable"
            Copy-Item -Path $exePath.FullName -Destination "portable\"
            Copy-Item -Path "icons\icon.png" -Destination "portable\" -ErrorAction SilentlyContinue
            Copy-Item -Path "README.md" -Destination "portable\" -ErrorAction SilentlyContinue
            Compress-Archive -Path "portable\*" -DestinationPath "FinanceQuest-Windows-Portable.zip" -Force
          }

      - name: Upload Portable ZIP
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: FinanceQuest-Windows-Portable
          path: FinanceQuest-Windows-Portable.zip
          if-no-files-found: ignore
