name: Release All Platforms

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            name: 'macOS'
          - platform: 'ubuntu-latest'
            name: 'Linux'
          - platform: 'windows-latest'
            name: 'Windows'

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ""
          TAURI_KEY_PASSWORD: ""
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'FinanceQuest Campus Edition ${{ github.ref_name }}'
          releaseBody: |
            ## FinanceQuest Campus Edition ${{ github.ref_name }}
            
            ### 📦 Installation Instructions
            
            **macOS:**
            - Download `FinanceQuest_*.dmg`
            - Open the DMG file and drag to Applications folder
            
            **Windows:**
            - Download `FinanceQuest_*_x64-setup.exe` (NSIS installer)
            - Or download `FinanceQuest_*_x64_en-US.msi` (MSI installer)
            - Run the installer
            
            **Linux:**
            - **AppImage**: Download `*.AppImage`, make executable (`chmod +x`), and run
            - **DEB**: Download `*.deb` and install with `sudo dpkg -i *.deb`
            
            ### ✨ What's New
            See [CHANGELOG.md](https://github.com/Rensjo/FinanceQuest_Campus-Edition/blob/main/CHANGELOG.md) for details.
            
            ### 🐛 Report Issues
            Found a bug? [Open an issue](https://github.com/Rensjo/FinanceQuest_Campus-Edition/issues/new)
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.platform == 'macos-latest' && '--target universal-apple-darwin' || '' }}
